# Paths
export ZDOTDIR="$HOME/.config/zsh"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export WEECHAT_HOME="$XDG_CONFIG_HOME/weechat"
export LESSHISTFILE="-"
export GOPATH="$XDG_DATA_HOME/go"

# Miscellaneous
export EDITOR="nvim"
export BROWSER="brave"
export READER="zathura"
export PAGER="less"
export OPENER="rifle"
export TERMINAL="alacritty"
export FILEMANAGER="lf"
export CALIBRE_USE_DARK_PALETTE=1

# nnn
export NNN_OPENER="rifle"
export NNN_BMS="h:~;p:~/pics;D:~/Downloads;w:~/work;d:~/docs;T:/tmp;b:~/books;H:/mnt/hdd;r:~/repos;"
export NNN_USE_EDITOR=1
# export NNN_PLUG=

# less colours
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

export LF_ICONS="di=󰉋 :\
fi=󰈔 :\
tw=󰈔 :\
ow=󰉋 :\
ln=󱅷 :\
or=❌:\
ex=󰆤 :\
*.txt=󰭷 :\
*.mom=󰭷 :\
*.me=󰭷 :\
*.ms=󰭷 :\
*.png=󰈟 :\
*.webp=󰈟 :\
*.ico=󰈟 :\
*.jpg=󰄀 :\
*.jpe=󰄀 :\
*.jpeg=󰄀 :\
*.gif=󰵸 :\
*.svg=🗺:\
*.tif=🖼:\
*.tiff=🖼:\
*.xcf=🖌:\
*.html=󰌝 :\
*.xml=󰗀 :\
*.gpg=󰌾 :\
*.css=󰌜 :\
*.pdf=󰈥 :\
*.djvu=󱓷 :\
*.epub=󰂺 :\
*.csv=󰸣 :\
*.tex=󰊄 :\
*.md=󰍔 :\
*.r=󰟔 :\
*.R=󰟔 :\
*.rmd=󰍔 :\
*.Rmd=󰍔 :\
*.m=📊:\
*.mp3=󰈣 :\
*.opus=󰈣 :\
*.ogg=󰈣 :\
*.m4a=󰈣 :\
*.flac=󰝚 :\
*.mkv=󰈰 :\
*.mp4=󰈰 :\
*.webm=󰴘 :\
*.mpeg=󰴘 :\
*.avi=󰴘 :\
*.zip=󰛫 :\
*.rar=󰀼 :\
*.7z=󰛫 :\
*.tar.gz=󰀼 :\
*.z64=󰊗 :\
*.v64=󰊗 :\
*.n64=󰊗 :\
*.gba=󰊗 :\
*.nes=󰊗 :\
*.gdi=󰊗 :\
*.1=󰋗 :\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=󰣇 :\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
*.jar=󰬷 :\
*.java=󰬷 :\
*.c=󰙱 :\
*.cpp=󰙲 :\
*.cc=󰙲 :\
*.py=󰌠 :\
*.hs=󰲒 :\
*.go=󰟓 :\
*.js=󰌞 :\
*.ruby=󰴭 :\
*.sol=󰡪 :\
*.wiki=󰖬 :\
*.json=󰘦 :\
"
