add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            
success_symbol = "[>](green)"
error_symbol = "[>](red)"
vicmd_symbol = "[>](yellow)"

[line_break]
disabled = true
